### PR TITLE
Pyg integration

### PR DESCRIPTION
**Pull request by cprimel**
Adding data to repo for easy replication (i.e., no need to download and decompress each time). Also, fixed incorrect column selection ('user' vs 'user_id') and reformatted the graph data (see commit message #2).

### CODE REVIEW

**Review by guptaviha — COMMENTED** [review]
Looks good but i strongly suggest that an easier way to handle the "user_id" vs "user" challenge would be to convert the headers in the CSVs (users.csv and tweets.csv) to "user". That way we won't have to make a dozen changes in the code - it also makes for a standardized column name rather than having to remember where we used "user" and where "user_id"

**Comment by cprimel** [comment]
There are only two functions which load data from the .csv files and each makes the same erroneous selection. The rest of the data loading process makes the correct selections / uses the relevant column name thereafter. So, this would fix both without need for making any further changes to the code and without editing the original data files. The problem with editing the data files is that you run into the problem that if someone, for whatever reason, uses the data from the original data repo rather than our edited .csv files, they would also need to edit the file adding an unnecessary obstacle to replication. The other option would be to include a script that verifies and edits the .csv headers before loading but that is more involved than just adding 6 characters to the codebase. As for us, if data is loaded anywhere, these functions should be the ones we are using anyways so there should not be any opportunity for tripping up.

**Comment by guptaviha** [comment]
Like your point about replication. Cool, let's merge it

**Review by guptaviha — APPROVED** [review]

**Comment by cprimel** [comment]
See commit messages for how i nerfed the model's F1 score by 5% by screwing up a DataFrame's index.  Now fixed and passes regression test / matches original build. Also, GATv2 integrated and available via CLI.

**Pull request merged**
